-- topics
update package_extra set value=replace(value, 'EmploymentandLabour', 'Employment And Labour') where key='topic';
update package_extra set value=replace(value, 'Agriculture', 'Agriculture') where key='topic';
update package_extra set value=replace(value, 'Arts,CultureandHistory', 'Arts, Culture and History') where key='topic';
update package_extra set value=replace(value, 'BusinessandIndustry', 'Business and Industry') where key='topic';
update package_extra set value=replace(value, 'EconomyandFinance', 'Economy and Finance') where key='topic';
update package_extra set value=replace(value, 'Education-AdultandContinuing', 'Education - Adult and Continuing') where key='topic';
update package_extra set value=replace(value, 'Education-EarlyChildhoodtoGrade12', 'Education - Early Childhood to Grade 12') where key='topic';
update package_extra set value=replace(value, 'Education-Post-SecondaryandSkillsTraining', 'Education - Post-Secondary and Skills Training') where key='topic';
update package_extra set value=replace(value, 'EmploymentandLabour', 'Employment and Labour') where key='topic';
update package_extra set value=replace(value, 'EnergyandNaturalResources', 'Energy and Natural Resources') where key='topic';
update package_extra set value=replace(value, 'Environment', 'Environment') where key='topic';
update package_extra set value=replace(value, 'FamiliesandChildren', 'Families and Children') where key='topic';
update package_extra set value=replace(value, 'Government', 'Government') where key='topic';
update package_extra set value=replace(value, 'HealthandWellness', 'Health and Wellness') where key='topic';
update package_extra set value=replace(value, 'HousingandUtilities', 'Housing and Utilities') where key='topic';
update package_extra set value=replace(value, 'ImmigrationandMigration', 'Immigration and Migration') where key='topic';
update package_extra set value=replace(value, 'InterprovincialandInternationalAffairs', 'Interprovincial and International Affairs') where key='topic';
update package_extra set value=replace(value, 'LawsandJustice', 'Laws and Justice') where key='topic';
update package_extra set value=replace(value, 'PersonswithDisabilities', 'Persons with Disabilities') where key='topic';
update package_extra set value=replace(value, 'PopulationandDemography', 'Population and Demography') where key='topic';
update package_extra set value=replace(value, 'Roads,DrivingandTransport', 'Roads, Driving and Transport') where key='topic';
update package_extra set value=replace(value, 'SafetyandEmergencyServices', 'Safety and Emergency Services') where key='topic';
update package_extra set value=replace(value, 'Science,TechnologyandInnovation', 'Science, Technology and Innovation') where key='topic';
update package_extra set value=replace(value, 'Seniors', 'Seniors') where key='topic';
update package_extra set value=replace(value, 'SocietyandCommunities', 'Society and Communities') where key='topic';
update package_extra set value=replace(value, 'SportsandRecreation', 'Sports and Recreation') where key='topic';
update package_extra set value=replace(value, 'Tourism&Parks', 'Tourism & Parks') where key='topic';
update package_extra set value=replace(value, 'AboriginalPeoples', 'Aboriginal Peoples') where key='topic';
-- audience
update package_extra set value=replace(value, 'aboriginal peoples', 'Aboriginal Peoples') where key='audience';
update package_extra set value=replace(value, 'artists', 'Artists') where key='audience';
update package_extra set value=replace(value, 'caregivers', 'Caregivers') where key='audience';
update package_extra set value=replace(value, 'children', 'Children') where key='audience';
update package_extra set value=replace(value, 'consumers', 'Consumers') where key='audience';
update package_extra set value=replace(value, 'educators', 'Educators') where key='audience';
update package_extra set value=replace(value, 'employees', 'Employees') where key='audience';
update package_extra set value=replace(value, 'employers', 'Employers') where key='audience';
update package_extra set value=replace(value, 'entrepreneur/selfemployed', 'Entrepreneur/Self-employed') where key='audience';
update package_extra set value=replace(value, 'entrepreneur/self-employed', 'Entrepreneur/Self-employed') where key='audience';
update package_extra set value=replace(value, 'farmers', 'Farmers') where key='audience';
update package_extra set value=replace(value, 'funding applicants', 'Funding Applicants') where key='audience';
update package_extra set value=replace(value, 'general public', 'General Public') where key='audience';
update package_extra set value=replace(value, 'government', 'Government') where key='audience';
update package_extra set value=replace(value, 'health care professionals', 'Health Care Professionals') where key='audience';
update package_extra set value=replace(value, 'immigrants', 'Immigrants') where key='audience';
update package_extra set value=replace(value, 'job seekers', 'Job Seekers') where key='audience';
update package_extra set value=replace(value, 'legal and law enforcement professionals', 'Legal and Law Enforcement professionals') where key='audience';
update package_extra set value=replace(value, 'lower-income earners', 'Lower-income Earners') where key='audience';
update package_extra set value=replace(value, 'lower income earners', 'Lower-income Earners') where key='audience';
update package_extra set value=replace(value, 'media', 'Media') where key='audience';
update package_extra set value=replace(value, 'nonprofit/voluntary organizations', 'Nonprofit/Voluntary Organizations') where key='audience';
update package_extra set value=replace(value, 'parents', 'Parents') where key='audience';
update package_extra set value=replace(value, 'persons with disabilities', 'Persons with Disabilities') where key='audience';
update package_extra set value=replace(value, 'researchers', 'Researchers') where key='audience';
update package_extra set value=replace(value, 'rural residents', 'Rural Residents') where key='audience';
update package_extra set value=replace(value, 'scientists', 'Scientists') where key='audience';
update package_extra set value=replace(value, 'seniors', 'Seniors') where key='audience';
update package_extra set value=replace(value, 'students', 'Students') where key='audience';
update package_extra set value=replace(value, 'travellers', 'Travellers') where key='audience';
update package_extra set value=replace(value, 'visitors to Alberta', 'Visitors to Alberta') where key='audience';
update package_extra set value=replace(value, 'youth', 'Youth') where key='audience';
-- pubtype
update package_extra set value=replace(value, 'assessment', 'Assessment') where key='pubtype';
update package_extra set value=replace(value, 'calendar', 'Calendar') where key='pubtype';
update package_extra set value=replace(value, 'contractualmaterialandagreements', 'Contractual Material and Agreements') where key='pubtype';
update package_extra set value=replace(value, 'contractual material and agreements', 'Contractual Material and Agreements') where key='pubtype';
update package_extra set value=replace(value, 'correspondence', 'Correspondence') where key='pubtype';
update package_extra set value=replace(value, 'dataset', 'Dataset') where key='pubtype';
update package_extra set value=replace(value, 'decision', 'Decision') where key='pubtype';
update package_extra set value=replace(value, 'educationalmaterial', 'Educational Material') where key='pubtype';
update package_extra set value=replace(value, 'educational material', 'Educational Material') where key='pubtype';
update package_extra set value=replace(value, 'event', 'Event') where key='pubtype';
update package_extra set value=replace(value, 'factsheet', 'Fact Sheet') where key='pubtype';
update package_extra set value=replace(value, 'fact sheet', 'Fact Sheet') where key='pubtype';
update package_extra set value=replace(value, 'financialreport', 'Financial Report') where key='pubtype';
update package_extra set value=replace(value, 'financial report', 'Financial Report') where key='pubtype';
update package_extra set value=replace(value, 'FOIPresponse', 'FOIP Response') where key='pubtype';
update package_extra set value=replace(value, 'FOIP response', 'FOIP Response') where key='pubtype';
update package_extra set value=replace(value, 'form', 'Form') where key='pubtype';
update package_extra set value=replace(value, 'geospatialmaterial', 'Geospatial Material') where key='pubtype';
update package_extra set value=replace(value, 'geospatial material', 'Geospatial Material') where key='pubtype';
update package_extra set value=replace(value, 'guide', 'Guide') where key='pubtype';
update package_extra set value=replace(value, 'interactiveresource', 'Interactive Resource') where key='pubtype';
update package_extra set value=replace(value, 'interactive resource', 'Interactive Resource') where key='pubtype';
update package_extra set value=replace(value, 'legislationandregulations', 'Legislation and Regulations') where key='pubtype';
update package_extra set value=replace(value, 'legislation and regulations', 'Legislation and Regulations') where key='pubtype';
update package_extra set value=replace(value, 'licencesandpermits', 'Licences and Permits') where key='pubtype';
update package_extra set value=replace(value, 'licences and permits', 'Licences and Permits') where key='pubtype';
update package_extra set value=replace(value, 'literarymaterial', 'Literary Material') where key='pubtype';
update package_extra set value=replace(value, 'literary material', 'Literary Material') where key='pubtype';
update package_extra set value=replace(value, 'mediarelease', 'Media Release') where key='pubtype';
update package_extra set value=replace(value, 'media release', 'Media Release') where key='pubtype';
update package_extra set value=replace(value, 'meetingmaterial', 'Meeting Material') where key='pubtype';
update package_extra set value=replace(value, 'meeting material', 'Meeting Material') where key='pubtype';
update package_extra set value=replace(value, 'movingimage', 'Moving Image') where key='pubtype';
update package_extra set value=replace(value, 'moving image', 'Moving Image') where key='pubtype';
update package_extra set value=replace(value, 'multimedia', 'Multimedia') where key='pubtype';
update package_extra set value=replace(value, 'notice', 'Notice') where key='pubtype';
update package_extra set value=replace(value, 'organizationaldescription', 'Organizational Description') where key='pubtype';
update package_extra set value=replace(value, 'organizational description', 'Organizational Description') where key='pubtype';
update package_extra set value=replace(value, 'policy', 'Policy') where key='pubtype';
update package_extra set value=replace(value, 'presentation', 'Presentation') where key='pubtype';
update package_extra set value=replace(value, 'referencematerial', 'Reference Material') where key='pubtype';
update package_extra set value=replace(value, 'reference material', 'Reference Material') where key='pubtype';
update package_extra set value=replace(value, 'report', 'Report') where key='pubtype';
update package_extra set value=replace(value, 'serial', 'Serial') where key='pubtype';
update package_extra set value=replace(value, 'sound', 'Sound') where key='pubtype';
update package_extra set value=replace(value, 'standard', 'Standard') where key='pubtype';
update package_extra set value=replace(value, 'statistics', 'Statistics') where key='pubtype';
update package_extra set value=replace(value, 'stillimage', 'Still Image') where key='pubtype';
update package_extra set value=replace(value, 'still image', 'Still Image') where key='pubtype';
update package_extra set value=replace(value, 'survey', 'Survey') where key='pubtype';

#frequencies
update package_extra set value=replace(value, 'Every2months', 'Every 2 months') where key='updatefrequency';
update package_extra set value=replace(value, 'Every4months', 'Every 4 months') where key='updatefrequency';
update package_extra set value=replace(value, 'Every2weeks', 'Every 2 weeks') where key='updatefrequency';
update package_extra set value=replace(value, 'Every5years', 'Every 5 years') where key='updatefrequency';
update package_extra set value=replace(value, 'Semiannual', 'Semi-annual') where key='updatefrequency';

#creators
update package_extra set value=replace(value, 'AboriginalRelations' , 'Aboriginal Relations') where key='creator';
update package_extra set value=replace(value, 'Agriculture and Forestry' , 'Agriculture and Forestry') where key='creator';
update package_extra set value=replace(value, 'AgricultureandRuralDevelopment' , 'Agriculture and Rural Development') where key='creator';
update package_extra set value=replace(value, 'Agriculture and RuralDevelopment' , 'Agriculture and Rural Development') where key='creator';
update package_extra set value=replace(value, 'CorporateHumanResources' , 'Corporate Human Resources') where key='creator';
update package_extra set value=replace(value, 'CultureandTourism' , 'Culture and Tourism') where key='creator';
update package_extra set value=replace(value, 'Education' , 'Education') where key='creator';
update package_extra set value=replace(value, 'Energy' , 'Energy') where key='creator';
update package_extra set value=replace(value, 'EnvironmentandSustainableResourceDevelopment' , 'Environment and Sustainable Resource Development') where key='creator';
update package_extra set value=replace(value, 'Environment and Parks' , 'Environment and Parks') where key='creator';
update package_extra set value=replace(value, 'ExecutiveCouncil' , 'Executive Council') where key='creator';
update package_extra set value=replace(value, 'GovernmentofAlberta' , 'Government of Alberta') where key='creator';
update package_extra set value=replace(value, 'Health' , 'Health') where key='creator';
update package_extra set value=replace(value, 'HumanServices' , 'Human Services') where key='creator';
update package_extra set value=replace(value, 'Infrastructure' , 'Infrastructure') where key='creator';
update package_extra set value=replace(value, 'InnovationandAdvancedEducation' , 'Innovation and Advanced Education') where key='creator';
update package_extra set value=replace(value, 'InternationalandIntergovernmentalRelations' , 'International and Intergovernmental Relations') where key='creator';
update package_extra set value=replace(value, '"Jobs' , 'Skills,TrainingandLabour"' ' , ' '"Jobs, Skills' , ' Training and Labour"') where key='creator';
update package_extra set value=replace(value, 'JusticeandSolicitorGeneral' , 'Justice and Solicitor General') where key='creator';
update package_extra set value=replace(value, 'MunicipalAffairs' , 'Municipal Affairs') where key='creator';
update package_extra set value=replace(value, 'PublicAffairsBureau' , 'Public Affairs Bureau') where key='creator';
update package_extra set value=replace(value, 'Seniors' , 'Seniors') where key='creator';
update package_extra set value=replace(value, 'ServiceAlberta' , 'Service Alberta') where key='creator';
update package_extra set value=replace(value, 'Status of Women' , 'Status of Women') where key='creator';
update package_extra set value=replace(value, 'Transportation' , 'Transportation') where key='creator';
update package_extra set value=replace(value, 'TreasuryBoardandFinance' , 'Treasury Board and Finance') where key='creator';
update package_extra set value=replace(value, 'LegislativeAssemblyOffice' , 'Legislative Assembly Office') where key='creator';
update package_extra set value=replace(value, 'OfficeoftheAuditorGeneral' , 'Office of the Auditor General') where key='creator';
update package_extra set value=replace(value, 'OfficeoftheChiefElectoralOfficer' , 'Office of the Chief Electoral Officer') where key='creator';
update package_extra set value=replace(value, 'OfficeoftheEthicsCommissioner' , 'Office of the Ethics Commissioner') where key='creator';
update package_extra set value=replace(value, 'OfficeoftheInformationandPrivacyCommissioner' , 'Office of the Information and Privacy Commissioner') where key='creator';
update package_extra set value=replace(value, 'OfficeoftheLieutenantGovernor' , 'Office of the Lieutenant Governor') where key='creator';
update package_extra set value=replace(value, 'OfficeoftheOmbudsman' , 'Office of the Ombudsman') where key='creator';
update package_extra set value=replace(value, 'Queen’s Printer' , 'Queen’s Printer') where key='creator';
update package_extra set value=replace(value, 'AboriginalAffairsandNorthernDevelopment(2000-2006)' , 'Aboriginal Affairs and Northern Development (2000-2006)') where key='creator';
update package_extra set value=replace(value, 'Aboriginal Affairs and Northern Development(2000-2006)' , 'Aboriginal Affairs and Northern Development (2000-2006)') where key='creator';
update package_extra set value=replace(value, 'AdvancedEducationandCareerDevelopment(1992-1999)' , 'Advanced Education and Career Development (1992-1999)') where key='creator';
update package_extra set value=replace(value, 'AdvancedEducationandManpower(1975-1983)' , 'Advanced Education and Manpower (1975-1983)') where key='creator';
update package_extra set value=replace(value, 'AdvancedEducationandTechnology(2006-2013)' , 'Advanced Education and Technology (2006-2013)') where key='creator';
update package_extra set value=replace(value, '"AdvancedEducation(1971-1975,1983-1992,2004-2006)"' , '"Advanced Education (1971-1975, 1983-1992, 2004-2006)"') where key='creator';
update package_extra set value=replace(value, 'AgricultureandFood(2006-2008)' , 'Agriculture and Food (2006-2008)') where key='creator';
update package_extra set value=replace(value, 'Agriculture(1905-1992)' , 'Agriculture (1905-1992)') where key='creator';
update package_extra set value=replace(value, '"Agriculture,Food,andRuralDevelopment(1992-2006)"' , '"Agriculture, Food, and Rural Development (1992-2006)"') where key='creator';
update package_extra set value=replace(value, 'AttorneyGeneral(1905-1992)' , 'Attorney General (1905-1992)') where key='creator';
update package_extra set value=replace(value, 'BusinessDevelopmentandTourism(1975-1979)' , 'Business Development and Tourism (1975-1979)') where key='creator';
update package_extra set value=replace(value, 'CareerDevelopmentandEmployment(1986-1992)' , 'Career Development and Employment (1986-1992)') where key='creator';
update package_extra set value=replace(value, 'ChildrenandYouthServices(2008-2011)' , 'Children and Youth Services (2008-2011)') where key='creator';
update package_extra set value=replace(value, 'ChildrensServices(1999-2008)' , 'Childrens Services (1999-2008)') where key='creator';
update package_extra set value=replace(value, 'CommunityandOccupationalHealth(1986-1989)' , 'Community and Occupational Health (1986-1989)') where key='creator';
update package_extra set value=replace(value, 'CommunityDevelopment(1992-2006)' , 'Community Development (1992-2006)') where key='creator';
update package_extra set value=replace(value, 'ConsumerAffairs(1973-1975)' , 'Consumer Affairs (1973-1975)') where key='creator';
update package_extra set value=replace(value, 'ConsumerandCorporateAffairs(1975-1992)' , 'Consumer and Corporate Affairs (1975-1992)') where key='creator';
update package_extra set value=replace(value, 'CulturalAffairs(1975-1980)' , 'Cultural Affairs (1975-1980)') where key='creator';
update package_extra set value=replace(value, 'CultureandCommunityServices(2011-2013)' , 'Culture and Community Services (2011-2013)') where key='creator';
update package_extra set value=replace(value, 'CultureandCommunitySpirit(2008-2011)' , 'Culture and Community Spirit (2008-2011)') where key='creator';
update package_extra set value=replace(value, 'CultureandMulticulturalism(1987-1992)' , 'Culture and Multiculturalism (1987-1992)') where key='creator';
update package_extra set value=replace(value, '"Culture(1980-1987,2013-2014)"' , '"Culture (1980-1987, 2013-2014)"') where key='creator';
update package_extra set value=replace(value, '"Culture,Youth,andRecreation(1971-1975)"' , '"Culture, Youth, and Recreation (1971-1975)"') where key='creator';
update package_extra set value=replace(value, 'EconomicDevelopmentandTourism(1992-1997)' , 'Economic Development and Tourism (1992-1997)') where key='creator';
update package_extra set value=replace(value, 'EconomicDevelopmentandTrade(1986-1992)' , 'Economic Development and Trade (1986-1992)') where key='creator';
update package_extra set value=replace(value, '"EconomicDevelopment(1979-1986,1997-2006)"' , '"Economic Development (1979-1986, 1997-2006)"') where key='creator';
update package_extra set value=replace(value, 'EmploymentandImmigration(2008-2011)' , 'Employment and Immigration (2008-2011)') where key='creator';
update package_extra set value=replace(value, '"Employment,ImmigrationandIndustry(2006-2008)"' , '"Employment, Immigration and Industry (2006-2008)"') where key='creator';
update package_extra set value=replace(value, 'EnergyandNaturalResources(1975-1986)' , 'Energy and Natural Resources (1975-1986)') where key='creator';
update package_extra set value=replace(value, 'EnvironmentandWater(2011-2013)' , 'Environment and Water (2011-2013)') where key='creator';
update package_extra set value=replace(value, '"Environment(1971-1992,1999-2011)"' , '"Environment (1971-1992, 1999-2011)"') where key='creator';
update package_extra set value=replace(value, 'EnvironmentalProtection(1992-1999)' , 'Environmental Protection (1992-1999)') where key='creator';
update package_extra set value=replace(value, 'FamilyandsocialServices(1989-1999)' , 'Family and social Services (1989-1999)') where key='creator';
update package_extra set value=replace(value, 'FederalandIntergovernmentalAffairs(1971-1997)' , 'Federal and Intergovernmental Affairs (1971-1997)') where key='creator';
update package_extra set value=replace(value, 'FinanceandEnterprise(2008-2011)' , 'Finance and Enterprise (2008-2011)') where key='creator';
update package_extra set value=replace(value, '"Finance(2001-2008,2011-2014)"' , '"Finance (2001-2008, 2011-2014)"') where key='creator';
update package_extra set value=replace(value, '"Forestry,Lands,andWildlife(1986-1993)"' , '"Forestry, Lands, and Wildlife (1986-1993)"') where key='creator';
update package_extra set value=replace(value, 'Gaming(1999-2006)' , 'Gaming (1999-2006)') where key='creator';
update package_extra set value=replace(value, '"GovernmentServices(1975-1983,1999-2006)"' , '"Government Services (1975-1983, 1999-2006)"') where key='creator';
update package_extra set value=replace(value, 'HealthandSocialDevelopment(1971-1975)' ,'Health and Social Development (1971-1975)') where key='creator';
update package_extra set value=replace(value, 'HealthandWellness(1999-2013)' ,'Health and Wellness (1999-2013)') where key='creator';
update package_extra set value=replace(value, 'HighwaysandTransport(1969-1975)' ,'Highways and Transport (1969-1975)') where key='creator';
update package_extra set value=replace(value, 'Highways(1951-1969)' ,'Highways (1951-1969)') where key='creator';
update package_extra set value=replace(value, 'HospitalsandMedicalCare(1975-1988)' ,'Hospitals and Medical Care (1975-1988)') where key='creator';
update package_extra set value=replace(value, 'HousingandPublicWorks(1975-1983)' ,'Housing and Public Works (1975-1983)') where key='creator';
update package_extra set value=replace(value, 'HousingandUrbanAffairs(2008-2011)' ,'Housing and Urban Affairs (2008-2011)') where key='creator';
update package_extra set value=replace(value, 'Housing(1983-1986)' ,'Housing (1983-1986)') where key='creator';
update package_extra set value=replace(value, 'HumanResourcesandEmployment(1999-2006)' ,'Human Resources and Employment (1999-2006)') where key='creator';
update package_extra set value=replace(value, 'IndustriesandLabour(1948-1959)' ,'Industries and Labour (1948-1959)') where key='creator';
update package_extra set value=replace(value, 'IndustryandCommerce(1972-1975)' ,'Industry and Commerce (1972-1975)') where key='creator';
update package_extra set value=replace(value, 'IndustryandDevelopment(1959-1968)' ,'Industry and Development (1959-1968)') where key='creator';
update package_extra set value=replace(value, 'IndustryandTourism(1968-1972)' ,'Industry and Tourism (1968-1972)') where key='creator';
update package_extra set value=replace(value, 'InfrastructureandTransportation(2004-2008)' ,'Infrastructure and Transportation (2004-2008)') where key='creator';
update package_extra set value=replace(value, 'InnovationandScience(1999-2006)' ,'Innovation and Science (1999-2006)') where key='creator';
update package_extra set value=replace(value, 'IntergovernmentalandAboriginalAffairs(1997-1999)' ,'Intergovernmental and Aboriginal Affairs (1997-1999)') where key='creator';
update package_extra set value=replace(value, '"International,IntergovernmentalandAboriginalRelations(2006-2008,2011-2013)"' ,'"International, Intergovernmental and Aboriginal Relations (2006-2008, 2011-2013)"') where key='creator';
update package_extra set value=replace(value, 'JusticeandAttorneyGeneral(1993-2011)' ,'Justice and Attorney General (1993-2011)') where key='creator';
update package_extra set value=replace(value, '"Justice(1992-1993,2011-2013)"' ,'"Justice (1992-1993, 2011-2013)"') where key='creator';
update package_extra set value=replace(value, '"Labour(1959-1972,1975-1999)"' ,'"Labour (1959-1972, 1975-1999)"') where key='creator';
update package_extra set value=replace(value, 'LandsandForests(1949-1975)' ,'Lands and Forests (1949-1975)') where key='creator';
update package_extra set value=replace(value, 'LandsandMines(1930-1949)' ,'Lands and Mines (1930-1949)') where key='creator';
update package_extra set value=replace(value, 'Learning(1999-2004)' ,'Learning (1999-2004)') where key='creator';
update package_extra set value=replace(value, 'ManpowerandLabour(1972-1975)' ,'Manpower and Labour (1972-1975)') where key='creator';
update package_extra set value=replace(value, 'Manpower and Labour (1972-1975)' ,'Manpower and Labour (1972-1975)') where key='creator';
update package_extra set value=replace(value, 'Manpower(1982-1986)' ,'Manpower (1982-1986)') where key='creator';
update package_extra set value=replace(value, 'MinesandMinerals(1949-1975)' ,'Mines and Minerals (1949-1975)') where key='creator';
update package_extra set value=replace(value, 'MunicipalAffairsandHousing(2006-2008)' ,'Municipal Affairs and Housing (2006-2008)') where key='creator';
update package_extra set value=replace(value, 'ProvincialSecretary(1905-1972)' ,'Provincial Secretary (1905-1972)') where key='creator';
update package_extra set value=replace(value, 'PublicHealth(1919-1967)' ,'Public Health (1919-1967)') where key='creator';
update package_extra set value=replace(value, 'PublicWelfare(1944-1969)' ,'Public Welfare (1944-1969)') where key='creator';
update package_extra set value=replace(value, 'PublicWorks(1905-1975)' ,'Public Works (1905-1975)') where key='creator';
update package_extra set value=replace(value, '"PublicWorks,Supply,andServices(1983-1999)"' ,'"Public Works, Supply, and Services (1983-1999)"') where key='creator';
update package_extra set value=replace(value, 'RecreationandParks(1979-1992)' ,'Recreation and Parks (1979-1992)') where key='creator';
update package_extra set value=replace(value, '"Recreation,Parks,andWildlife(1975-1979)"' ,'"Recreation, Parks, and Wildlife (1975-1979)"') where key='creator';
update package_extra set value=replace(value, 'ResourceDevelopment(1999-2001)' ,'Resource Development (1999-2001)') where key='creator';
update package_extra set value=replace(value, 'RestructuringandGovernmentEfficiency(2004-2006)' ,'Restructuring and Government Efficiency (2004-2006)') where key='creator';
update package_extra set value=replace(value, 'Revenue(2001-2004)' ,'Revenue (2001-2004)') where key='creator';
update package_extra set value=replace(value, 'SeniorsandCommunitySupports(2004-2011)' ,'Seniors and Community Supports (2004-2011)') where key='creator';
update package_extra set value=replace(value, 'SocialDevelopment(1969-1971)' ,'Social Development (1969-1971)') where key='creator';
update package_extra set value=replace(value, 'SocialServicesandCommunityHealth(1975-1986)' ,'Social Services and Community Health (1975-1986)') where key='creator';
update package_extra set value=replace(value, 'SocialServices(1986-1989)' ,'Social Services (1986-1989)') where key='creator';
update package_extra set value=replace(value, 'SolicitorGeneralandPublicSafety(2006-2008)' ,'Solicitor General and Public Safety (2006-2008)') where key='creator';
update package_extra set value=replace(value, '"SolicitorGeneralandPublicSecurity(1973-1992,2001-2006,2008-2013)"' ,'"Solicitor General and Public Security (1973-1992, 2001-2006, 2008-2013)"') where key='creator';
update package_extra set value=replace(value, '"SustainableResourceDevelopment(2001-2006,2006-2013)"' ,'"Sustainable Resource Development (2001-2006, 2006-2013)"') where key='creator';
update package_extra set value=replace(value, 'TelephonesandUtilities(1973-1975)' ,'Telephones and Utilities (1973-1975)') where key='creator';
update package_extra set value=replace(value, 'TourismandSmallBusiness(1979-1986)' ,'Tourism and Small Business (1979-1986)') where key='creator';
update package_extra set value=replace(value, 'Tourism(1986-1992)' ,'Tourism (1986-1992)') where key='creator';
update package_extra set value=replace(value, '"Tourism,Parks,andRecreation(1992,2008-2014)"' ,'"Tourism, Parks, and Recreation (1992, 2008-2014)"') where key='creator';
update package_extra set value=replace(value, '"Tourism,Parks,RecreationandCulture(2006-2008)"' ,'"Tourism, Parks, Recreation and Culture (2006-2008)"') where key='creator';
update package_extra set value=replace(value, 'TradeandIndustry(1934-1948)' ,'Trade and Industry (1934-1948)') where key='creator';
update package_extra set value=replace(value, 'TransportationandUtilities(1986-1999)' ,'Transportation and Utilities (1986-1999)') where key='creator';
update package_extra set value=replace(value, 'TreasuryBoardandEnterprise(2011-2013)' ,'Treasury Board and Enterprise (2011-2013)') where key='creator';
update package_extra set value=replace(value, '"TreasuryBoard(2004-2006,2008-2011,2013-2014)"' ,'"Treasury Board (2004-2006, 2008-2011, 2013-2014)"') where key='creator';
update package_extra set value=replace(value, 'Treasury(1905-2001)' ,'Treasury (1905-2001)') where key='creator';
update package_extra set value=replace(value, 'UtilitiesandTelecommunications(1983-1986)' ,'Utilities and Telecommunications (1983-1986)') where key='creator';
update package_extra set value=replace(value, 'UtilitiesandTelephones(1975-1983)' ,'Utilities and Telephones (1975-1983)') where key='creator';
update package_extra set value=replace(value, 'Utilities(1986)' ,'Utilities (1986)') where key='creator';

##Update publications date modified
update package_extra set key=replace(key, 'modifieddate' ,'date_modified') where key='modifieddate';
